image: node

cache:
  paths:
  - node_modules/

stages:
  - truffle-tests

smart_contracts:
  stage: truffle-tests
  services:
   - trufflesuite/ganache-cli -e 1000000
  script:
   - npm install truffle
   - ./node_modules/truffle/build/cli.bundled.js test
